website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, session, url_for
from flask_login import login_required, current_user
from werkzeug.utils import redirect
from .models import ContactEmail, Note, Contact, Task, PhoneNumber, ContactEmail, Iqtest
from . import db
import json
import os
import secrets
from werkzeug.utils import secure_filename



# from flask_wtf.file import FileField 
views = Blueprint('views', __name__)


AVATAR_FOLDER = 'static/images/avatars/'

# ---Avatar upload---


UPLOAD_FOLDER = '/path/to/the/uploads'
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join('static/images/avatars', picture_fn)
    form_picture.save(picture_path)
    return picture_fn


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


  

# --- Home page
@views.route('/')
def home():

    return render_template("home.html", user=current_user)



# --- show Notes and new note
@views.route('/notes', methods=['GET', 'POST'])
@login_required
def notes():
    # count_row = session.query(Note).count()
    
    if request.method == 'POST':
        from random import choice
        rancolor = choice(["color1", "color2", "color3", "color4", "color5", "color6",\
             "color7", "color8", "color9", "color10", "color11", "color12"])

        title = request.form.get('title')
        note = request.form.get('note')

        if len(note) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note, title=title, color=rancolor, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')

    return render_template("note.html", user=current_user)


@views.route('/note-edit', methods = ['GET', 'POST'])
def note_update():
 
    if request.method == 'POST':
        my_data = Note.query.get(request.form.get('note_id'))
 
        my_data.title = request.form['title']
        my_data.data = request.form['note_data']

        db.session.commit()
        flash("Note Updated Successfully")
 
    return redirect(url_for('views.notes'))


@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})


# --- show contact and New Contact
@views.route('/contacts', methods=['GET', 'POST'])
@login_required
def contacts():

    # my_data = Contact.query.get(request.form.get('contact_id'))
    # avatar = my_data.avatar
    # image_file = url_for('static', filename='images/avatars/' + avatar)

    if request.method == 'POST':

        from random import choice
        list_color = ["blue", "red", "green", "orange", "cyan", "pink", "cardinal", 
                      "dark green", "magenta", "purple", "dark magenta", "fawn", "flame"]
        rancolor = choice(list_color) 

        first_name = request.form.get('name')
        last_name = request.form.get('sname')
        address = request.form.get('address')
        website = request.form.get('website')
        telegram = request.form.get('telegram')

        PhoneList = request.form.getlist('addphone[]')
        EmailList = request.form.getlist('addemail[]')
        file = request.files['avatar']

        # contact.phone_numbers | map(attribute='number') | list

      
        if len(first_name) < 1:
            flash('Name is too short!', category='error')
        elif len(last_name) < 1:
            flash('Surname is too short!', category='error')
        else:
            phone_numbers = list(map(lambda number: PhoneNumber(number=number), PhoneList))
            contact_email = list(map(lambda email: ContactEmail(email=email), EmailList))
            
            new_contact = Contact(name=first_name.capitalize(), sname=last_name.capitalize(), phone_numbers=phone_numbers, \
             contact_email=contact_email, address=address.capitalize(), siteurl=website, telegram=telegram, t_color=rancolor, user_id=current_user.id)
           
            db.session.add(new_contact)
            db.session.commit()

            # # Avatar upload
            # if 'avatar' not in request.files:
            #     flash(f"No file part {request.files}" )
            #     return redirect(request.url)
            # file = request.files['avatar']
            # # If the user does not select a file, the browser submits an
            # # empty file without a filename.
            # if file.filename == '':
            #     flash('No selected file')
            #     return redirect(request.url)
            
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file.save(os.path.join('website/static/images/avatars/', filename))
                
                # flash("Contact Updated Successfully")

                return redirect(url_for('views.contacts', name=filename))


            flash('Contact added!', category='success')

    return render_template("contact.html", user=current_user)


# --- Edit contact 
@views.route('/contact-edit', methods = ['GET', 'POST'])
def contact_update():
 
    if request.method == 'POST':

        my_data = Contact.query.get(request.form.get('contact_id'))
        
        file = request.files['avatar']
        my_data.name = request.form.get('name')
        my_data.sname = request.form.get('sname')
        my_data.pnumber = request.form.get('pnumber')
        my_data.avatar = file.filename

        # for contact in current_user.contacts:
        #     contact.

        db.session.commit()
        

        # Avatar upload
        # check if the post request has the file part
        if 'avatar' not in request.files:
            flash(f"No file part {request.files}" )
            return redirect(request.url)
        
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join('website/static/images/avatars/', filename))
            
            flash("Contact Updated Successfully")

            return redirect(url_for('views.contacts', name=filename))

    return redirect(url_for('views.contacts'))

# -- delete Contact
@views.route('/delete-contact', methods=['POST'])
def delete_contact():
    contact = json.loads(request.data)
    contactId = contact['contactId']
    contact = Contact.query.get(contactId)
    if contact:
        if contact.user_id == current_user.id:
            db.session.delete(contact)
            db.session.commit()

    return jsonify({})


# --- show todo and new todo
@views.route('/todo', methods=['GET', 'POST'])
@login_required
def todo():

    if request.method == 'POST':
        title = request.form.get('title')
        task = request.form.get('task')
        status = request.form.get('status')
        due_date = request.form.get('date')
        due_time = request.form.get('time')        

        if len(title) < 1:
            flash('Task title is too short!', category='error')
        elif len(task) < 1:
            flash('Task description is too short', category='error') 
        else:
            new_task = Task(title=title, task=task, status=status, due_date=due_date, due_time=due_time, user_id=current_user.id)
            db.session.add(new_task)
            db.session.commit()
            flash(f"\"{title}\" is successfully added!", category='success')

    return render_template("todo.html", user=current_user)


# --- Edit Task 
@views.route('/task-edit', methods = ['GET', 'POST'])
def todo_update():
 
    if request.method == 'POST':
        my_data = Task.query.get(request.form.get('task_id'))

        my_data.title = request.form.get('title')
        my_data.task = request.form.get('task')
        my_data.status = request.form.get('status')
        my_data.due_date = request.form.get('due_date')
        my_data.due_time = request.form.get('due_time')
        
        db.session.commit()
        flash(f"\"{my_data.title}\" Updated Successfully")

    return redirect(url_for('views.todo'))


# -- delete Task
@views.route('/delete-task', methods=['POST'])
def delete_task():
    task = json.loads(request.data)
    taskId = task['taskid']
    task = Task.query.get(taskId)
    if task:
        if task.user_id == current_user.id:
            db.session.delete(task)
            db.session.commit()

    return jsonify({})


@views.route('/iqtest', methods=['GET', 'POST'])
@login_required
def IQtest():

    QuestionList = IQtest.query.all()
    Question = IQtest.query.first()

    if request.method == 'POST':

        testid = request.form.get('testid')
        answer = request.form.get('answer')

    return render_template("iqtest.html", QuestionList=QuestionList, Question=Question, user=current_user)


# --- Edit Iq test
# @views.route('/iqtest-edit', methods = ['GET', 'POST'])
# def AddTest():
 
    # if request.method == 'POST':

#to change color of question buttons and disable 
def setStatus(qlist):
    qAttempt=[]
    strval=session['result'].strip()
    ans=strval.split(',')
    for i in range(int(len(ans)/2)):
        qAttempt.append(int(ans[2*i]))  
    
    for rw in qlist:
        if rw.qid in qAttempt:
            rw.bcol='green'   # set color
            rw.status='disabled' # disable


@views.route("/showQuest/<int:Qid>")
def showQuest(Qid):
    questList=IQtest.query.all()

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
     -->
     
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <link
      rel="stylesheet"
      href="../static/css/bootstrap.css"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="../static/css/colors.css"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="../static/css/base.css"
      crossorigin="anonymous"
    />
    <style>
          [data-letters]:before {
          content:attr(data-letters);
          display:inline-block;
          font-size:1em;
          width:2.5em;
          height:2.5em;
          line-height:2.5em;
          text-align:center;
          border-radius:50%;
          vertical-align:middle;
          margin-right:1em;
          color:white;
          background: tomato;
      }
      .bi-pen:hover{
          color: red;

      }
    </style>

    <title>{% block title %}Home{% endblock %}</title>
    
  </head>
  <body class="back_img">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/"><i class=" bi bi-house"></i></a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container ">{% block content %} {% endblock %}</div>



    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>

  </body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home page{% endblock %} {% block content
    %}
    <h3 align="center" class="text-white">Your Dashboard</h3>

    {% for user in users %}
        
    {% endfor %}
    <div class="app_container">
        
        <div class="app_link">
            <object data="../static/css/bootstrap-icons-1.6.1/list-task.svg" class="app-object violet_svg"> </object>
            <a href="/todo"><button class="btn btn-light">To Do</button></a>
        </div>
        
        <div class="app_link">
            <object data="../static/css/bootstrap-icons-1.6.1/pen-fill.svg" width="60" class="violet_svg" width="90" height="90"> </object>
            <a href="/notes"><button class="btn btn-light">Notes</button></a>
        </div>
    
        <div class="app_link">
            <object data="../static/css/bootstrap-icons-1.6.1/person-fill.svg" class="app-object violet_svg"> </object>
            <a href="/contacts"><button class="btn btn-light">Contacts</button></a>
        </div>

        <div class="app_link">
            <object data="../static/css/bootstrap-icons-1.6.1/question.svg" class="app-object violet_svg"> </object>
            <a href="/iqtest"><button class="btn btn-light">IQ Test</button></a>
        </div>

    </div>
    
    
    

    {% endblock %}
    

website/templates/indextest.html
<html>  
 <head>  
  <title>Python Flask Add Remove Input Fields Dynamically with jQuery and save to database MySQLdb</title>  
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<style>
.input-wrapper div {
    margin-bottom: 10px;
}
.remove-input {
    margin-top: 10px;
    margin-left: 15px;
    vertical-align: text-bottom;
}
.add-input {
    margin-top: 10px;
    margin-left: 10px;
    vertical-align: text-bottom;
}
</style>
 </head>  
 <body>  
  <div style="width:85%;padding:50px;">  
    <h2>Python Flask Add Remove Input Fields Dynamically with jQuery and save to database MySQLdb</h2>  

    <form method="POST">
        <div class="input-wrapper">
            <div><p>Name :</p>
            <input type="text" name="field[]" value=""/>
            <a href="javascript:void(0);" class="add-input" title="Add input"> add </a>
            </div>
        </div>
        <input type="submit" name="cmdsubmit">
    </form>
   
  </div>  
<script>
$(document).ready(function(){
    var max_input_fields = 10;
    var add_input = $('.add-input');
    var input_wrapper = $('.input-wrapper');
    var new_input = '<div class="box"><input type="text" name="field[]" value=""/><a href="javascript:void(0);" class="remove-input" title="Remove input"> remove</a></div>';
    var add_input_count = 1; 
    $(add_input).click(function(){
        if(add_input_count < max_input_fields){
            add_input_count++; 
            $(input_wrapper).append(new_input); 
        }
    });
    $(input_wrapper).on('click', '.remove-input', function(e){
        e.preventDefault();
        $(this).parent('div').remove();
        add_input_count--;
    });
});
</script>
 </body>  
</html>  

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<div id="login-row" class="row justify-content-center align-items-center ">
  <div id="login-column" class="col-md-6">
    <div id="login-box" class="col-md-12">
      <form method="POST">
        <h3 align="center" class="text-white">Login</h3>
        
        <div class="input-group mb-3 ">
          <i class="input-group-text bi bi-envelope-fill input-btn-r"></i>
          <input type="text"  name="email" id="email" class="form-control" placeholder=" Email or phone number">
        </div>
      
        <div class="input-group mb-3">
          <i class="input-group-text bi bi-lock-fill input-btn-r"></i>
          <input type="password"  name="password" id="password" class="form-control" placeholder=" Password">
        </div>
      
        <br />
        <div class="col text-center">
          <button type="submit" class="btn btn-primary ">Login</button>
          
          <br/>
          <b class="text-white">OR</b>
        </div>
      </form>
      <br/>
      <div class="col text-center">
        <a href="#" class="btn btn-primary small-txt"><i class=" bi bi-facebook font-s h5"></i> Sign in with Facebook</a>
        <a href="#" class="btn btn-danger small-txt"><i class=" bi bi-google h6"></i> Sign in with Google</a>
      </div>

      <div class="col text-center">
        <p>Not registered? <a href="\sign-up">Sign Up</a></p>
      </div>
      
    </div>
  </div>
</div>

{% endblock %}

website/templates/note.html
{% extends "base.html" %} {% block title %}Notes{% endblock %} {% block content
%}
<br>
<!-- Note home page  -->
<button 
    class="btn btn-light" 
    data-toggle="modal" 
    data-target="#newnote"><object data="../static/css/bootstrap-icons-1.6.1/plus-square.svg" 
    width="16" height="16"> </object> Add note</button>
<h1 align="center">Notes</h1>
<table class="table table-hover" id="contacts">
  <thead>
    <tr>
      <th>Note</th>
      <th>Date</th>

      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for note in user.notes %}
    <tr class="success">
      <td>
        <div class="size_note {{ note.color }} d-block"></div>
        <button class="btn btn-light d-inline" style="margin-left: 100px;" data-toggle="modal" data-target="#shownote{{ note.id }}">{{ note.title}}</button>
      </td>
      <td>{{ note.date.strftime('%Y-%m-%d %H:%M') }}</td>
      <td>
        <!-- <button 
          class="btn btn-primary bi bi-pen"
          style="color: white;" 
          title="edit"
          data-toggle="modal" 
          data-target="#mymodal{{ note.id }}"
          >edit
      </button> -->
      <a class="btn btn-primary" href="/note-edit/{{ note.id }}" data-toggle="modal" data-target="#note_edit{{ note.id }}">edit</a>
      <button 
      type="button" 
      class="btn btn-outline-danger" 
      onClick="deleteNote({{ note.id }})">delete
      </button></td>
    </tr>

    <!--  Update note Modal -->
    <div class="modal fade" id="note_edit{{ note.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Update Note</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action="{{url_for('views.note_update')}}" method="POST"> 
              <label for="title">Title</label>
              <input type="text" placeholder="title" id="title" name="title" value="{{note.title}}">
              <input type="hidden" name="note_id" value="{{note.id}}">
              <br>
              <label for="note_data">Description</label>
              <textarea 
                class="form-control" 
                name="note_data" id="note_data">{{ note.data }}
              </textarea>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>

    <!--show note Modal -->
    <div class="modal fade" id="shownote{{ note.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"> {{ note.title }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="border-left border-info" style="padding-left: 10px;">
                {{ note.data }}
            </div>        
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    {% endfor %}
  </tbody>
</table>


<!--New note Modal -->
<div class="modal fade" id="newnote" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New note</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST">
          <label for="title">Title</label>
          <input type="text" placeholder="title" id="title" name="title">
          <br>
          <label for="note">Description</label>
          <textarea name="note" id="note" class="form-control"></textarea>
          <br />
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Save & Close</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </form>        
      </div>
    </div>
  </div>
</div>






{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}

<div id="login-row" class="row justify-content-center align-items-center ">
  <div id="login-column" class="col-md-6">
    <div id="login-box" class="col-md-12">
      <form method="POST"  enctype="multipart/form-data">
        <h3 align="center" class="text-white">Sign Up</h3>
      
        <div class="input-group mb-3">
          <i class="input-group-text bi bi-envelope input-btn-r"></i>
          <input type="text"  name="email" id="email" class="form-control" placeholder=" Email or phone number">
        </div>
      
        <div class="input-group mb-3">
          <i class="input-group-text bi bi-person input-btn-r"></i>
          <input type="text"  name="name" id="name" class="form-control" placeholder=" Name">
          <input type="text"  name="sname" id="sname" class="form-control" placeholder=" Surname">
        </div>
      
        <div class="input-group mb-3">
          <i class="input-group-text bi bi-shield-lock input-btn-r"></i>
          <input type="password"  name="password1" id="password1" class="form-control" placeholder=" Password">
          <input type="password"  name="password2" id="password2" class="form-control" placeholder=" Password again">
        </div>
      
      
        <div class="form-group">
          <!-- <label for="avatar">Your photo</label><br> -->
          <input
            type="file"
            class="btn btn-outline-info text-hide"
            id="avatar"
            name="avatar"
            >
        </div>
      
        <br />
        <div class="text-center">
          <button type="submit" class="btn btn-primary ">Submit</button>
          <p>Have an account? <a href="\login">Login</a></p>
        </div>
      </form>          
    </div>
  </div>
</div>

{% endblock %}

website/templates/test.html
<p>{{ fullname }}</p>

website/templates/todo.html
{% extends "base.html" %} {% block title %}ToDo{% endblock %} 
{% block content %}
<br>
<button 
    class="btn btn-light" 
    data-toggle="modal" 
    data-target="#newtodo"><object data="../static/css/bootstrap-icons-1.6.1/journal-plus.svg" 
    width="16" height="16"> </object> Add Task</button>
<h1 align="center">ToDo</h1>
<table class="table table-hover" id="Todo">
  <thead>
    <tr>
      <th>ToDo</th>
      <th>Status</th>
      <th>Due Date</th>
      <th>Due Time</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for todo in user.tasks %}
    <tr class="success">
      <td>
        <button 
            class="btn btn-light d-inline" 
            style="margin-left: 100px;" 
            data-toggle="modal" 
            data-target="#showtask{{ todo.id }}">{{ todo.title}}
          </button>
      </td>
      {% if todo.status == 'Not yet' %}
        <td><span class="Notyet">{{ todo.status}}</span> </td>

      {% elif todo.status == 'Done' %}
      <td><span class="Done">{{ todo.status}}</span> </td>

      {% else %}
        <td><span class="Inproccess">{{ todo.status}}</span> </td>
      {% endif %}
      
      <td>{{ todo.due_date}}</td>
      <td>{{ todo.due_time}}</td>
      <td>
        <a class="btn btn-primary" 
           href="/task-edit/{{ todo.id }}" 
           data-toggle="modal" 
           data-target="#edittodo{{ todo.id }}">edit</a>
        

        <button 
           type="button" 
           class="btn btn-outline-danger" 
           onClick="deleteTask({{ todo.id }})">delete
             <span aria-hidden="true" class="bi bi-trash" style="color: red;" title="delete"></span>
           </button>
          </td>
    </tr>



    
<!--Edit task Modal -->
<div class="modal fade" id="edittodo{{ todo.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Task</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{{url_for('views.todo_update')}}" method="POST">
          <label for="title">Title</label>
          <input type="hidden" name="task_id" value="{{todo.id}}">
          <input type="text" placeholder="Task title" id="title" name="title" value="{{ todo.title }}">
          <br>
          <label for="note">Description</label>
          <textarea name="task" id="task" class="form-control">{{ todo.task }}</textarea>
          <br>
          
          <label for="status">Status</label>
          <select name="status" id="status" selected="{{ todo.status }}">
            <option name="Not yet" value="Not yet">Not yet</option>
            <option name="Done" value="Done">Done</option>
            <option name="In Proccess" value="In Proccess">In Proccess</option>
          </select>
          <br>

          <label for="date">Due date</label>
          <input type="date" id="due_date" name="due_date" value="{{ todo.due_date }}">
          <br>
          <label for="time" >Due time</label>
          <input type="time" id="due_time" name="due_time"   value="{{ todo.due_time }}">
          
          <br />
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Update & Close</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </form>        
      </div>
    </div>
  </div>
</div>
    {% endfor %}
  </tbody>
</table>



<!--New task Modal -->
<div class="modal fade" id="newtodo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Task</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST">
          <label for="title">Title</label>
          <input type="text" placeholder="Task title" id="title" name="title">
          <br>
          <label for="note">Description</label>
          <textarea name="task" id="task" class="form-control"></textarea>
          <br>
          
          <label for="status">Status</label>
          <select name="status" id="status">
            <option value="Not yet">Not yet</option>
            <option value="Done">Done</option>
            <option value="In Proccess">In Proccess</option>
          </select>
          <br>
          <label for="date">Due date</label>
          <input type="date" id="date" name="date">
          <br>
          <label for="time" >Due time</label>
          <input type="time" name="time" id="time">

          <br />
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Save & Close</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </form>        
      </div>
    </div>
  </div>
</div>


{% endblock %}
    